### ISSUE TITLE
Unable to open the softsynth device: No such file or directory

### ISSUE THREAD

**Issue by cinmay** [linux-speakup/espeakup#1]
Hi. when I try to run espeakup I get:
# espeakup -d

Unable to open the softsynth device: No such file or directory

I'm running
espeakup 0.7,1
espeak 1.42.04 
kernel 2.6.36

**Comment by ilyaigpetrov** [comment]
This helped me on KDE Neon (Ubuntu):
```
sudo modprobe speakup
sudo modprobe speakup_soft
```

**Comment by sthibaul** [comment]
yes, most probably the user was missing loading speakup_soft (no need to load speakup, it will be an automatic dependency of speakup_soft)
