### ISSUE TITLE
is upstream activ?

### ISSUE THREAD

**Issue by alex19EP** [linux-speakup/espeakup#17]
hello @williamh looking at commits, lack of releases and some unclosed issues It seems to me that you do not have much time to maintain espeakup therefore I offer my help. I will gladly become a maintainer of this project.

**Comment by williamh** [comment]
I have been doing a lot of work-related things lately, but let me catch up on issues etc and see where we are. Ultimately I am interested in working with espeak-ng which isn't in my distro yet, so I want to look into packaging it. Also, I want to consider moving to a meson-based build instead of just make.

**Comment by alex19EP** [comment]
ok @williamh nice to hear from you. i provided a simple PR #16  which will close one of issues.
as for build system. i don't understand why switching to meson is necessary.

**Comment by sthibaul** [comment]
@williamh it's warm to hear from you! Welcome back :)

**Comment by alex19EP** [comment]
if anyone is interested. I merged open pr's into my fork.
will create a new tag on the weekend.

is some distribution maintainer interested in working with me?

**Comment by sthibaul** [comment]
Rather than maintenance on another personal repository, we should probably move to a shared repository on

https://github.com/linux-speakup/espeakup

What do you think @williamh ?

**Comment by alex19EP** [comment]
> Rather than maintenance on another personal repository, we should probably move to a shared repository

absolutely agree. the current state of upstream is very depressing for me.

**Comment by alex19EP** [comment]
FYI i working on meson support at my fork
https://github.com/alex19EP/espeakup/pull/7
currently it strongly related to other changes in my master branch, but when the situation with upstream will be clearer. I will gladly do a PR.

**Comment by williamh** [comment]
Here's a quick update. Yes, I do plan to bring upstream back; I have just been very busy with work related things. I will get back to it asap.

**Comment by alex19EP** [comment]
ok. now that espeakup is in the organization and @williamh  and I have the same access rights, we can close this.
